CREATE SEQUENCE IF NOT EXISTS empleados_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS empleados (
    clave VARCHAR(32) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(100) NOT NULL
);
